features_dir = 'feature/'
models_dir = 'model/'
data_dir = 'data/'
fire_words = True
fire_shapes = False
fire_embeddings = True
fire_clusters = False
fire_e1_context = True
fire_e2_context = True
before_e2 = False  # defaults to padding after e1 if set to False
task_number = '1.1'
